### ISSUE TITLE
Deisgn Mockup

### ISSUE THREAD

**Issue by Azhari12** [ALTA-CAPSTONE-GROUP1/e-proposal#1]

**Comment by Azhari12** [comment]
On this part, After we know MPV and user flow on this app, we that FE discussion with BE about what interface looks like in general overview. FE try to make mockup of interface this app based BE confirmation, what is BE needed on interface we try  make mockup of them.

**Comment by projack14** [comment]
Figma Mockup Link  (https://www.figma.com/file/o8ZmTq7YDpstHXnlLwOwm2/Untitled?type=design&node-id=0-1&t=fvQgERqelQo2WHII-0)
